[package]
name = "libcommons"
version = "0.5.0"
edition = "2024"

[features]
default = []
full = ["str", "dirs", "extra_traits", "lock", "io", "result"]
str = []
dirs = []
extra_traits = []
lock = []
io = []
result = []
matrix = ["nightly"]
nightly = []
